// src/frontend/components/vue/Organization.vue
<script setup lang="ts">
import { ref, computed, onMounted, watch } from 'vue';
import { createClient } from '../../clients/vue-client';

// CreateOrganizationForm Props
interface CreateOrgProps {
    component: 'create';
    baseUrl?: string;
    className?: string;
}

// OrganizationSwitcher Props
interface SwitcherProps {
    component: 'switcher';
    baseUrl?: string;
    currentOrgId?: string;
    className?: string;
}

// InviteMemberForm Props
interface InviteProps {
    component: 'invite';
    baseUrl?: string;
    className?: string;
}

type Props = CreateOrgProps | SwitcherProps | InviteProps;

const props = defineProps<Props>();

const emit = defineEmits<{
    (e: 'success', data?: any): void;
    (e: 'error', error: string): void;
}>();

const client = computed(() => createClient(props.baseUrl));

// Create Organization Form State
const orgName = ref('');
const orgSlug = ref('');
const createLoading = ref(false);
const createError = ref<string | null>(null);
const createSuccess = ref(false);

// Organization Switcher State
const orgs = ref<any[]>([]);
const switcherLoading = ref(true);
const selectedOrgId = ref('');

// Invite Member Form State
const inviteEmail = ref('');
const inviteRole = ref('member');
const inviteLoading = ref(false);
const inviteError = ref<string | null>(null);
const inviteSuccess = ref(false);

// Auto-slugify for create form
watch(orgName, (val) => {
    if (props.component === 'create' && !orgSlug.value) {
        orgSlug.value = val.toLowerCase().replace(/\s+/g, '-');
    }
});

// Load orgs for switcher
onMounted(async () => {
    if (props.component === 'switcher') {
        try {
            const { data } = await client.value.organization.list({});
            if (data) orgs.value = data;
            if ((props as SwitcherProps).currentOrgId) {
                selectedOrgId.value = (props as SwitcherProps).currentOrgId!;
            }
        } catch (err) {
            console.error('Failed to load organizations', err);
        } finally {
            switcherLoading.value = false;
        }
    }
});

const handleCreateOrg = async () => {
    createLoading.value = true;
    createError.value = null;
    createSuccess.value = false;

    try {
        const result = await client.value.organization.create({
            name: orgName.value,
            slug: orgSlug.value,
        });
        if (result.error) throw result.error;
        orgName.value = '';
        orgSlug.value = '';
        createSuccess.value = true;
        emit('success', result.data);
    } catch (err: any) {
        createError.value = err.message || 'Failed to create organization';
        emit('error', createError.value);
    } finally {
        createLoading.value = false;
    }
};

const handleSwitchOrg = async () => {
    if (!selectedOrgId.value) return;
    await client.value.organization.setActive({ organizationId: selectedOrgId.value });
    emit('success', selectedOrgId.value);
};

const handleInvite = async () => {
    inviteLoading.value = true;
    inviteError.value = null;
    inviteSuccess.value = false;

    try {
        const result = await client.value.organization.inviteMember({
            email: inviteEmail.value,
            role: inviteRole.value as any,
        });
        if (result.error) throw result.error;
        inviteEmail.value = '';
        inviteSuccess.value = true;
        emit('success', result.data);
    } catch (err: any) {
        inviteError.value = err.message || 'Invitation failed';
        emit('error', inviteError.value);
    } finally {
        inviteLoading.value = false;
    }
};
</script>

<template>
    <!-- Create Organization Form -->
    <form v-if="component === 'create'" :class="`ca-form ${(props as CreateOrgProps).className || ''}`" @submit.prevent="handleCreateOrg">
        <h3 class="ca-subtitle">Create Organization</h3>
        <div class="ca-input-group">
            <label class="ca-label">Organization Name</label>
            <input
                v-model="orgName"
                type="text"
                class="ca-input"
                required
                placeholder="Acme Corp"
            />
        </div>
        <div class="ca-input-group">
            <label class="ca-label">Slug</label>
            <input
                v-model="orgSlug"
                type="text"
                class="ca-input"
                required
                placeholder="acme-corp"
            />
        </div>
        <div v-if="createError" class="ca-error">{{ createError }}</div>
        <div v-if="createSuccess" class="ca-success-message" style="padding: 0.75rem; background: #d1fae5; border-radius: 6px; color: #065f46; text-align: center;">
            Organization created!
        </div>
        <button type="submit" class="ca-button" :disabled="createLoading">
            {{ createLoading ? 'Creating...' : 'Create Organization' }}
        </button>
    </form>

    <!-- Organization Switcher -->
    <div v-else-if="component === 'switcher'" :class="`ca-org-switcher ${(props as SwitcherProps).className || ''}`">
        <label class="ca-label">Select Organization</label>
        <select 
            v-model="selectedOrgId" 
            class="ca-select" 
            :disabled="switcherLoading"
            @change="handleSwitchOrg"
        >
            <option v-if="switcherLoading" value="" disabled>Loading...</option>
            <option v-else-if="orgs.length === 0" value="" disabled>No organizations</option>
            <template v-else>
                <option value="" disabled>Select an organization</option>
                <option v-for="org in orgs" :key="org.id" :value="org.id">
                    {{ org.name }}
                </option>
            </template>
        </select>
    </div>

    <!-- Invite Member Form -->
    <form v-else-if="component === 'invite'" :class="`ca-form ${(props as InviteProps).className || ''}`" @submit.prevent="handleInvite">
        <h3 class="ca-subtitle">Invite Member</h3>
        <div class="ca-input-group">
            <label class="ca-label">Email Address</label>
            <input
                v-model="inviteEmail"
                type="email"
                class="ca-input"
                required
                placeholder="colleague@example.com"
            />
        </div>
        <div class="ca-input-group">
            <label class="ca-label">Role</label>
            <select v-model="inviteRole" class="ca-select">
                <option value="member">Member</option>
                <option value="admin">Admin</option>
                <option value="owner">Owner</option>
            </select>
        </div>
        <div v-if="inviteError" class="ca-error">{{ inviteError }}</div>
        <div v-if="inviteSuccess" class="ca-success-message" style="padding: 0.75rem; background: #d1fae5; border-radius: 6px; color: #065f46; text-align: center;">
            Invitation sent!
        </div>
        <button type="submit" class="ca-button" :disabled="inviteLoading">
            {{ inviteLoading ? 'Sending Invite...' : 'Send Invite' }}
        </button>
    </form>
</template>

// src/frontend/components/react/Organization.tsx
import React, { useState, useEffect } from 'react';
import { authClient } from '../../client';

interface BaseOrgProps {
    client?: typeof authClient;
    className?: string;
    onSuccess?: (data?: any) => void;
    onError?: (error: string) => void;
}

// --- Create Organization Form ---

export const CreateOrganizationForm: React.FC<BaseOrgProps> = ({
    client = authClient,
    className,
    onSuccess,
    onError
}) => {
    const [name, setName] = useState('');
    const [slug, setSlug] = useState('');
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        try {
            const result = await client.organization.create({
                name,
                slug,
            });
            if (result.error) throw result.error;
            setName('');
            setSlug('');
            onSuccess?.(result.data);
        } catch (err: any) {
            onError?.(err.message || "Failed to create organization");
        } finally {
            setLoading(false);
        }
    };

    return (
        <form onSubmit={handleSubmit} className={`ca-form ${className || ''}`}>
            <h3 className="ca-subtitle">Create Organization</h3>
            <div className="ca-input-group">
                <label className="ca-label">Organization Name</label>
                <input
                    type="text"
                    className="ca-input"
                    value={name}
                    onChange={(e) => {
                        setName(e.target.value);
                        // Auto-slugify
                        if (!slug) setSlug(e.target.value.toLowerCase().replace(/\s+/g, '-'));
                    }}
                    required
                    placeholder="Acme Corp"
                />
            </div>
            <div className="ca-input-group">
                <label className="ca-label">Slug</label>
                <input
                    type="text"
                    className="ca-input"
                    value={slug}
                    onChange={(e) => setSlug(e.target.value)}
                    required
                    placeholder="acme-corp"
                />
            </div>
            <button type="submit" className="ca-button" disabled={loading}>
                {loading ? 'Creating...' : 'Create Organization'}
            </button>
        </form>
    );
};

// --- Organization Switcher ---

export const OrganizationSwitcher: React.FC<BaseOrgProps & { currentOrgId?: string }> = ({
    client = authClient,
    className,
    currentOrgId,
    onSuccess
}) => {
    const [orgs, setOrgs] = useState<any[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchOrgs = async () => {
            const { data } = await client.organization.list({});
            if (data) setOrgs(data);
            setLoading(false);
        };
        fetchOrgs();
    }, [client]);

    const handleSwitch = async (orgId: string) => {
        await client.organization.setActive({ organizationId: orgId });
        onSuccess?.(orgId);
    };

    if (loading) return <div className="ca-loading">Loading...</div>;

    return (
        <div className={`ca-org-switcher ${className || ''}`}>
            <label className="ca-label">Select Organization</label>
            <select
                className="ca-select"
                value={currentOrgId || ''}
                onChange={(e) => handleSwitch(e.target.value)}
            >
                <option value="" disabled>Select an organization</option>
                {orgs.map(org => (
                    <option key={org.id} value={org.id}>{org.name}</option>
                ))}
            </select>
        </div>
    );
};

// --- Invite Member Form ---

export const InviteMemberForm: React.FC<BaseOrgProps & { organizationId?: string }> = ({
    client = authClient,
    className,
    onSuccess,
    onError
}) => {
    const [email, setEmail] = useState('');
    const [role, setRole] = useState('member');
    const [loading, setLoading] = useState(false);

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setLoading(true);
        try {
            const result = await client.organization.inviteMember({
                email,
                role: role as any,
            });
            if (result.error) throw result.error;
            setEmail('');
            onSuccess?.(result.data);
        } catch (err: any) {
            onError?.(err.message || 'Invitation failed');
        } finally {
            setLoading(false);
        }
    };

    return (
        <form onSubmit={handleSubmit} className={`ca-form ${className || ''}`}>
            <h3 className="ca-subtitle">Invite Member</h3>
            <div className="ca-input-group">
                <label className="ca-label">Email Address</label>
                <input
                    type="email"
                    className="ca-input"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    required
                    placeholder="colleague@example.com"
                />
            </div>
            <div className="ca-input-group">
                <label className="ca-label">Role</label>
                <select
                    className="ca-select"
                    value={role}
                    onChange={(e) => setRole(e.target.value)}
                >
                    <option value="member">Member</option>
                    <option value="admin">Admin</option>
                    <option value="owner">Owner</option>
                </select>
            </div>
            <button type="submit" className="ca-button" disabled={loading}>
                {loading ? 'Sending Invite...' : 'Send Invite'}
            </button>
        </form>
    );
};
