// src/frontend/components/ResetPasswordForm.tsx
import React, { useState } from 'react';
import { authClient } from '../client';

interface ResetPasswordFormProps {
    /** The reset token from the URL query parameter */
    token: string | null;
    client?: typeof authClient;
    onSuccess?: () => void;
    onBackToLogin?: () => void;
    className?: string;
    title?: React.ReactNode;
    width?: 'default' | 'compact' | 'wide';
}

export const ResetPasswordForm: React.FC<ResetPasswordFormProps> = ({
    token,
    client = authClient,
    onSuccess,
    onBackToLogin,
    className,
    title,
    width = 'default'
}) => {
    const [password, setPassword] = useState('');
    const [confirmPassword, setConfirmPassword] = useState('');
    const [loading, setLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);
    const [success, setSuccess] = useState(false);

    let widthClass = '';
    if (width === 'compact') widthClass = 'ca-width-compact';
    else if (width === 'wide') widthClass = 'ca-width-wide';
    else widthClass = 'ca-width-default';

    const titleContent = title ? (
        typeof title === 'string' ? <h2 className="ca-title">{title}</h2> : title
    ) : (
        <h2 className="ca-title">Set New Password</h2>
    );

    // Handle missing token
    if (!token) {
        return (
            <div className={`ca-container ${widthClass} ${className || ''}`}>
                {titleContent}
                <div className="ca-error-message">
                    <svg className="ca-error-icon" viewBox="0 0 24 24" width="48" height="48">
                        <circle cx="12" cy="12" r="10" fill="#EF4444" />
                        <path d="M12 8v4M12 16h.01" stroke="white" strokeWidth="2" strokeLinecap="round" />
                    </svg>
                    <h3 className="ca-error-title">Invalid or Missing Token</h3>
                    <p className="ca-error-text">
                        The password reset link is invalid or has expired.
                        Please request a new password reset.
                    </p>
                </div>
                {onBackToLogin && (
                    <div className="ca-footer">
                        <button className="ca-link" onClick={onBackToLogin} type="button">
                            Back to Sign In
                        </button>
                    </div>
                )}
            </div>
        );
    }

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();

        if (password !== confirmPassword) {
            setError('Passwords do not match');
            return;
        }

        if (password.length < 8) {
            setError('Password must be at least 8 characters');
            return;
        }

        setLoading(true);
        setError(null);

        try {
            const { error } = await client.resetPassword({
                token,
                newPassword: password
            });
            if (error) throw error;
            setSuccess(true);
            onSuccess?.();
        } catch (err: any) {
            setError(err.message || 'Failed to reset password');
        } finally {
            setLoading(false);
        }
    };

    if (success) {
        return (
            <div className={`ca-container ${widthClass} ${className || ''}`}>
                {titleContent}
                <div className="ca-success-message">
                    <svg className="ca-success-icon" viewBox="0 0 24 24" width="48" height="48">
                        <circle cx="12" cy="12" r="10" fill="#10B981" />
                        <path d="M8 12l2.5 2.5L16 9" stroke="white" strokeWidth="2" fill="none" strokeLinecap="round" strokeLinejoin="round" />
                    </svg>
                    <h3 className="ca-success-title">Password Reset Successful</h3>
                    <p className="ca-success-text">
                        Your password has been successfully reset. You can now sign in with your new password.
                    </p>
                </div>
                {onBackToLogin && (
                    <div className="ca-footer">
                        <button className="ca-link" onClick={onBackToLogin} type="button">
                            Sign In
                        </button>
                    </div>
                )}
            </div>
        );
    }

    return (
        <div className={`ca-container ${widthClass} ${className || ''}`}>
            {titleContent}
            <p className="ca-subtitle">
                Enter your new password below.
            </p>
            <form onSubmit={handleSubmit} className="ca-form">
                <div className="ca-input-group">
                    <label className="ca-label" htmlFor="password">New Password</label>
                    <input
                        id="password"
                        type="password"
                        className="ca-input"
                        value={password}
                        onChange={(e) => setPassword(e.target.value)}
                        placeholder="At least 8 characters"
                        minLength={8}
                        required
                    />
                </div>

                <div className="ca-input-group">
                    <label className="ca-label" htmlFor="confirmPassword">Confirm Password</label>
                    <input
                        id="confirmPassword"
                        type="password"
                        className="ca-input"
                        value={confirmPassword}
                        onChange={(e) => setConfirmPassword(e.target.value)}
                        placeholder="Confirm your password"
                        required
                    />
                </div>

                {error && <div className="ca-error">{error}</div>}

                <button type="submit" className="ca-button" disabled={loading}>
                    {loading ? 'Resetting...' : 'Reset Password'}
                </button>
            </form>

            {onBackToLogin && (
                <div className="ca-footer">
                    <button className="ca-link" onClick={onBackToLogin} type="button">
                        Back to Sign In
                    </button>
                </div>
            )}
        </div>
    );
};

// src/frontend/components/vue/ResetPasswordForm.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { createClient } from '../../clients/vue-client';

interface Props {
    token?: string | null;
    baseUrl?: string;
    backToLoginUrl?: string;
    title?: string;
    width?: 'default' | 'compact' | 'wide';
}

const props = withDefaults(defineProps<Props>(), {
    title: 'Set New Password',
    width: 'default',
});

const emit = defineEmits<{
    (e: 'success'): void;
    (e: 'error', error: string): void;
}>();

const client = computed(() => createClient(props.baseUrl));

const password = ref('');
const confirmPassword = ref('');
const loading = ref(false);
const error = ref<string | null>(null);
const success = ref(false);

const widthClass = computed(() => {
    if (props.width === 'compact') return 'ca-width-compact';
    if (props.width === 'wide') return 'ca-width-wide';
    return 'ca-width-default';
});

const hasToken = computed(() => !!props.token);

const handleSubmit = async () => {
    if (password.value !== confirmPassword.value) {
        error.value = 'Passwords do not match';
        return;
    }

    if (password.value.length < 8) {
        error.value = 'Password must be at least 8 characters';
        return;
    }

    loading.value = true;
    error.value = null;

    try {
        const { error: err } = await client.value.resetPassword({
            token: props.token!,
            newPassword: password.value
        });
        if (err) throw err;
        success.value = true;
        emit('success');
    } catch (err: any) {
        error.value = err.message || 'Failed to reset password';
        emit('error', error.value);
    } finally {
        loading.value = false;
    }
};
</script>

<template>
    <div :class="`ca-container ${widthClass}`">
        <h2 class="ca-title">{{ title }}</h2>

        <!-- Missing Token State -->
        <template v-if="!hasToken">
            <div class="ca-error-message">
                <svg class="ca-error-icon" viewBox="0 0 24 24" width="48" height="48">
                    <circle cx="12" cy="12" r="10" fill="#EF4444" />
                    <path d="M12 8v4M12 16h.01" stroke="white" stroke-width="2" stroke-linecap="round" />
                </svg>
                <h3 class="ca-error-title">Invalid or Missing Token</h3>
                <p class="ca-error-text">
                    The password reset link is invalid or has expired.
                    Please request a new password reset.
                </p>
            </div>
            <div v-if="backToLoginUrl" class="ca-footer">
                <a :href="backToLoginUrl" class="ca-link">Back to Sign In</a>
            </div>
        </template>

        <!-- Success State -->
        <template v-else-if="success">
            <div class="ca-success-message">
                <svg class="ca-success-icon" viewBox="0 0 24 24" width="48" height="48">
                    <circle cx="12" cy="12" r="10" fill="#10B981" />
                    <path d="M8 12l2.5 2.5L16 9" stroke="white" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round" />
                </svg>
                <h3 class="ca-success-title">Password Reset Successful</h3>
                <p class="ca-success-text">
                    Your password has been successfully reset. You can now sign in with your new password.
                </p>
            </div>
            <div v-if="backToLoginUrl" class="ca-footer">
                <a :href="backToLoginUrl" class="ca-link">Sign In</a>
            </div>
        </template>

        <!-- Form State -->
        <template v-else>
            <p class="ca-subtitle">Enter your new password below.</p>
            <form class="ca-form" @submit.prevent="handleSubmit">
                <div class="ca-input-group">
                    <label class="ca-label" for="password">New Password</label>
                    <input
                        id="password"
                        v-model="password"
                        type="password"
                        class="ca-input"
                        placeholder="At least 8 characters"
                        minlength="8"
                        required
                    />
                </div>

                <div class="ca-input-group">
                    <label class="ca-label" for="confirmPassword">Confirm Password</label>
                    <input
                        id="confirmPassword"
                        v-model="confirmPassword"
                        type="password"
                        class="ca-input"
                        placeholder="Confirm your password"
                        required
                    />
                </div>

                <div v-if="error" class="ca-error">{{ error }}</div>

                <button type="submit" class="ca-button" :disabled="loading">
                    {{ loading ? 'Resetting...' : 'Reset Password' }}
                </button>
            </form>

            <div v-if="backToLoginUrl" class="ca-footer">
                <a :href="backToLoginUrl" class="ca-link">Back to Sign In</a>
            </div>
        </template>
    </div>
</template>
